services:
  - type: web
    name: backend-2
    runtime: python
    repo: https://github.com/pg460482-cell/backend
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    plan: free
    pythonVersion: 3.11
